### ISSUE TITLE
[Q] How to use docx-apply-cell-styles ?

### ISSUE THREAD

**Issue by m-guggenmos** [pandocker/pandocker-lua-filters#5]
Do I understand correctly that the lua filter `docx-apply-cell-styles.lua` allows defining a custom paragraph style to a table for docx output? This would be exactly, what I'm looking for, but I don't know how to use the filter.

For instance, given a simple markdown table...

```Markdown

| header1 | header2 |
|---------|---------|
|row1,col1|row1,col2|

```

...how do I have to extend this code to apply a custom paragraph style `MyTable` to this table (assuming I have defined the `MyTable` style in my reference.docx)?

**Comment by K4zuki** [comment]
Hi, thank you for asking!

In short, you only add yaml block to your code. no change is required to your table.

---

Please check `metadata-file.yaml` in `lua` directory. Line 40~:
```yaml
table-cell-styles:
  header-default: "Table Head Left"
  header-left: "Table Head Left"
  header-center: "Table Head Center"
  header-right: "Table Head Right"
  body-default: "Table Body Left"
  body-left: "Table Body Left"
  body-center: "Table Body Center"
  body-right: "Table Body Right"
```
This is a list of paragraph style settings, that apply to each Header and Body cell with Left/Right/Center/Default alignments, respectively. (In the most cases Default == Left)

When your `reference.docx` has `MyTable`, and you want to apply it to the whole table, add following lines to your config yaml or code itself.
```yaml
table-cell-styles:
  header-default: "MyTable"
  header-left: "MyTable"
  body-default: "MyTable"
  body-left: "MyTable"
```
Please note when your table has center or right-aligned columns, `Table Head Center`/`Table Head Right`/`Table Body Center`/`Table Body Right` styles will be applied.
If your `reference.docx` doesn't have them, the filter adds it to the output DOCX file anyway. These styles will inherit the `Body` style.
Also please note `MyTable` alignment **overrides** column alignment in your code (style definition wins).

Hope this answers your question,
Kazuki / K4zuki

**Comment by m-guggenmos** [comment]
Hi Kazuki,
Thanks so much for this immediate and detailed response, very helpful!

I now tried it with your instructions and it works. However, I realize it is not what I had in mind -- my goal was to apply _separate styles to different tables_, regardless of their alignment. I guess this would require a separate lua filter.

One question: where/how would you recommend setting the lua path for pandocker? I didn't figure out how to do it (e.g. setting an environment variable did not work), so in the end I created a symbolic link in /usr/local/share/lua/5.3 to my local installation of pandocker. Surley there must be a better way.

Thanks and Best.

**Comment by K4zuki** [comment]
Hi @m-guggenmos ,

This filter is unable to apply different styles table by table. One set of styles applies to all tables in the code.

The installation path is hard-coded point to `<sys.prefix>/share/lua/5.3/pandocker` in `setup.py` right now. The primary target of this package is/was to use pandoc's official docker image, whose Lua version is 5.3. Maybe Lua's searching path (`LUAPATH`?) could help somehow at installation but I don't have much idea for this.

Your goal could be achieved by a filter and Div/s like:
- Each Table is placed inside a Div; this Div needs to have a certain class (such as `secton1-table`, `section2-table`...).
    - one Div may have multiple classes so it may co-exist with other filters.
- User sets up yaml config block for each class.
```yaml
table-cell-styles:
  section1-table:
    header-default: "Table Head Left 1"
    header-left: "Table Head Left 1"
    header-center: "Table Head Center 1"
    header-right: "Table Head Right 1"
    body-default: "Table Body Left 1"
    body-left: "Table Body Left 1"
    body-center: "Table Body Center 1"
    body-right: "Table Body Right 1"
  section2-table:
    header-default: "Table Head Left 2"
    header-left: "Table Head Left 2"
    header-center: "Table Head Center 2"
    header-right: "Table Head Right 2"
    body-default: "Table Body Left 2"
    body-left: "Table Body Left 2"
    body-center: "Table Body Center 2"
    body-right: "Table Body Right 2"
```
- the filter searches all Divs in a Doc; if the Div has Table, it searches for a set of styles corresponding to class, and applies style for each cell. When no definition is found, it applies the default style set or simply ignore.
- `lua/docx-custom-span-styles.lua` could be a hint to implement. Table doesn't have attribute itself so Div is required (unlike Span)
